"""add recap email template and guest recap_sent_at

Revision ID: 53a453d570b9
Revises: e6ff10a66bd6
Create Date: 2026-08-23 16:44:30.513363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a453d570b9'
down_revision = 'e6ff10a66bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recap_email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recap_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_column('recap_sent_at')

    op.drop_table('recap_email_templates')
    # ### end Alembic commands ###
