"""add event options for date/time choice

Revision ID: 6380d5e8bf4d
Revises: 9ac3662f3f95
Create Date: 2026-08-17 19:44:44.028636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6380d5e8bf4d'
down_revision = '9ac3662f3f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_option_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event_options', ['event_option_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_option_id')

    op.drop_table('event_options')
    # ### end Alembic commands ###
