"""add email template signature

Revision ID: 8afc172381af
Revises: 6380d5e8bf4d
Create Date: 2026-08-22 19:06:20.900665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afc172381af'
down_revision = '6380d5e8bf4d'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.Text(), nullable=False, server_default=''))
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.alter_column('signature', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_column('signature')

    # ### end Alembic commands ###
